### ISSUE TITLE
please push to a maven public repository

### ISSUE THREAD

**Issue by i30817** [edmund-wagner/junrar#15]

**Comment by beothorn** [comment]
If the owner of this project give me permission, and there's no copyright issues, I could upload it.

**Comment by edmund-wagner** [comment]
you are now a contibutor. i've already prepared the poms a bit, but got scared of all the documentation at sonatype ;)

**Comment by beothorn** [comment]
Edmund, it seems I only have permission to deploy artifacts with my groupid (com.github.beothorn) . 
For now the dependency looks like this:
<dependency>
  <groupId>com.github.beothorn</groupId>
  <artifactId>junrar</artifactId>
  <version>0.6</version>
</dependency>
The release takes more or less three hours to be available, I'll test it tomorrow, but it should already be working when you read this.

If you want to deploy it under your group id the pom is ready, only the group id must be changed to com.github.edmund-wagner . 
You have to create a issue like this one on sonatype https://issues.sonatype.org/browse/OSSRH-3539 . It usually take two days until they close the issue, but after this you have permission to upload anything on your groupid.
Then you have to create a gpg key (https://docs.sonatype.org/display/Repository/How+To+Generate+PGP+Signatures+With+Maven)
gpg --gen-key
and run
mvn release:clean
mvn release:prepare
mvn release:perform
After you go to their web app on https://oss.sonatype.org and follow 8a. on https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

Thanks

**Comment by edmund-wagner** [comment]
hmm i think it would be good to create an organization on github and publish as com.github.junrar/junrar

**Comment by junrar** [comment]
Created the junrar user on github, opened this issue: https://issues.sonatype.org/browse/OSSRH-4241 on sonatype, as soon as they give me permission I'll release the project.

**Comment by beothorn** [comment]
<dependency>
  <groupId>com.github.junrar</groupId>
  <artifactId>junrar</artifactId>
  <version>0.7</version>
</dependency>

**Comment by edmund-wagner** [comment]
good job :)
