### ISSUE TITLE
Join testutil and unrar

### ISSUE THREAD

**Issue by beothorn** [edmund-wagner/junrar#16]
On my project I'm using the class ExtractArchive that is on the testutil module. It seems that this class could be moved to the unrar module, and JUnRarTestUtil.java could go to src/test on unrar too, if the generate-testdata.sh was converted to java.
This would make it easier to import/deploy junrar.
Is it ok to do this?
Thanks

**Comment by edmund-wagner** [comment]
sure go ahead.
