### ISSUE TITLE
Eclipse project files

### ISSUE THREAD

**Issue by Rogiel** [edmund-wagner/junrar#7]
I don't think eclipse specific project files should be included into the repository. They are volatile and sometimes not compatible with older versions of eclipse. Besides the fact that other might not use Eclipse at all.

Instead, I propose that should be encouraged the usage of Maven 2 eclipse plugin (Right click project -> Maven -> Update project configuration) or, as a last resort, the maven eclipse plugin (`mvn eclipse:eclipse`) to generate project files.

**Comment by edmund-wagner** [comment]
you're right. removed that stuff
